"""
Data Module - Dataset Definitions
Contains training and test datasets for sentiment analysis
"""

# Training Dataset (30 sentences inspired by "The Sparrow" themes)
training_sentences = [
    "The linguist decoded patterns in the alien transmission.",
    "They hoped this mission would reveal God's greater purpose.",
    "The attack came without warning in the darkness.",
    "Father Emilio believed faith would guide their journey.",
    "The spacecraft's hull was designed for interstellar travel.",
    "Violence erupted as territorial boundaries were violated.",
    "Sofia dreamed of making first contact with another species.",
    "The airlock mechanism required precise engineering calculations.",
    "Suffering tested the limits of their religious conviction.",
    "The Jesuit mission sought knowledge beyond the stars.",
    "Navigation systems plotted coordinates through deep space.",
    "The massacre left survivors traumatized and broken.",
    "Revenge consumed those who had lost everything.",
    "The probe's sensors detected complex signal patterns.",
    "Anne yearned for understanding across the cosmic divide.",
    "The telescope array captured stunning celestial imagery.",
    "Betrayal shattered the trust between species forever.",
    "Jimmy anticipated breakthrough discoveries on the alien world.",
    "Battle cries echoed through the alien settlement.",
    "The habitat modules provided life support systems.",
    "Emilio planned redemption through continued service.",
    "The observatory stood as humanity's window to infinity.",
    "Conflict destroyed any chance of peaceful coexistence.",
    "The young priest studied xenolinguistic communication protocols.",
    "Her determination drove scientific progress forward relentlessly.",
    "The ambush cost them their most skilled navigator.",
    "They aspired to bridge the gap between worlds.",
    "The ship's framework incorporated revolutionary composite materials.",
    "The raid left the expedition decimated and stranded.",
    "She dreamed of understanding alien consciousness itself.",
]

manual_labels = [
    "C", "A", "B", "A", "C", "B", "A", "C", "A", "A",
    "C", "B", "B", "C", "A", "C", "B", "A", "B", "C",
    "A", "C", "B", "C", "A", "B", "A", "C", "B", "A",
]

# Extended Test Dataset (expandable pool - inspired by "The Sparrow")
all_test_sentences = [
    # Category A: Hope/Aspiration (40 sentences)
    "The mission promised unprecedented scientific discoveries.",
    "He vowed to find meaning in the cosmic journey.",
    "The crew celebrated receiving signals from Rakhat.",
    "She hoped to establish peaceful interspecies communication.",
    "They dreamed of understanding alien musical traditions.",
    "The scientists anticipated revolutionary linguistic breakthroughs.",
    "Emilio aspired to serve God among the stars.",
    "The expedition team looked forward to landfall.",
    "Anne wished for her research to bridge two worlds.",
    "Father Sandoz envisioned a new era of faith.",
    "The Jesuits hoped their mission would succeed.",
    "Sofia planned to document the first contact.",
    "The priest sought redemption through continued devotion.",
    "The musicians dreamed of sharing beauty across species.",
    "Jimmy longed to see alien civilization firsthand.",
    "The crew prayed for safe passage through space.",
    "She aspired to decode the alien language completely.",
    "The linguists yearned to master xenocommunication.",
    "They hoped the aliens would welcome their arrival.",
    "The Father wished for divine guidance on Rakhat.",
    "Emilio dreamed of finding God's purpose revealed.",
    "The team anticipated mutual understanding and peace.",
    "Anne vowed to protect indigenous culture from harm.",
    "The missionaries prayed for wisdom and compassion.",
    "Sandoz hoped to unite humanity with alien faith.",
    "They longed for meaningful contact with the Jana'ata.",
    "The young priest dreamed of spiritual enlightenment.",
    "Sofia planned to establish cultural exchange protocols.",
    "The crew hoped to return home with knowledge.",
    "She wished for humanity to learn from aliens.",
    "The astronomers looked forward to observing new stars.",
    "Jimmy aspired to compose music with alien harmonies.",
    "The expedition hoped for breakthrough discoveries daily.",
    "Father Emilio envisioned a thriving interstellar mission.",
    "They dreamed of escaping Earth's limitations forever.",
    "The researchers hoped their work would endure.",
    "Anne planned a comprehensive xenoanthropological study.",
    "The crew wished for abundant resources on Rakhat.",
    "The Jesuit hoped to prove faith transcends worlds.",
    "They aspired to build lasting bonds between species.",
    # Category B: Conflict/Violence (40 sentences)
    "The brutal interrogation left Emilio physically broken.",
    "Blood marked the ground where the massacre occurred.",
    "The Jana'ata warriors attacked with overwhelming force.",
    "Alien soldiers captured the defenseless expedition members.",
    "Weapons clashed as territorial disputes exploded violently.",
    "The ambush came without warning in darkness.",
    "Flames consumed the settlement as refugees fled screaming.",
    "The executioner prepared the captive for punishment.",
    "Raiders destroyed the camp and killed the crew.",
    "The torture chamber echoed with Sandoz's screams.",
    "Projectiles rained down upon the fleeing humans.",
    "The alien forces slaughtered everyone in their path.",
    "War destroyed everything the mission accomplished.",
    "The assassin struck Askama swiftly at night.",
    "Blood soaked the alien soil after battle.",
    "Enemies burned supplies to starve the survivors.",
    "The mob attacked with primitive brutal weapons.",
    "Soldiers dragged prisoners to holding cells.",
    "The rebellion was crushed with savage efficiency.",
    "Rioters destroyed scientific equipment and resources.",
    "The guards prepared captives for execution rituals.",
    "Mercenaries killed without hesitation or conscience.",
    "The siege left the expedition decimated and helpless.",
    "Warriors charged with deadly intent and rage.",
    "The compound fell after a devastating assault.",
    "Betrayal led to murder and violent retribution.",
    "The confrontation ended with fatal injuries inflicted.",
    "Bandits ambushed the supply expedition mercilessly.",
    "The raid left nothing but ruins and bodies.",
    "Combatants fought savagely with alien weaponry.",
    "The invasion brought death and total destruction.",
    "Assassins poisoned food supplies systematically.",
    "The battle raged for days with horrific casualties.",
    "Soldiers burned shelters with people trapped inside.",
    "The massacre spared no one from violence.",
    "Warriors trampled victims beneath armored feet.",
    "The conflict escalated into genocidal warfare.",
    "Rebels attacked the settlement under cover of darkness.",
    "The conquerors showed no mercy to survivors.",
    "Violence erupted suddenly in the crowded alien city.",
    # Category C: Science/Technology (40 sentences)
    "The mission was dedicated to advancing scientific knowledge.",
    "They carefully installed the complex sensor arrays.",
    "The engineers measured every trajectory precisely.",
    "The chief technician inspected each system carefully.",
    "Antenna arrays rose majestically toward the stars.",
    "The spacecraft's foundation was engineered deep and strong.",
    "Technicians programmed intricate navigation patterns.",
    "The support struts reinforced the ship's hull.",
    "Workers assembled modular habitat components systematically.",
    "The vessel's main corridor stretched impressively long.",
    "Engineers calibrated instruments for atmospheric analysis.",
    "The docking bay intersected the corridor at right angles.",
    "Equipment racks climbed to maximize storage space.",
    "The observatory curved gracefully behind the command deck.",
    "Fuel was mixed with precise chemical proportions.",
    "The storage bay was constructed beneath the main deck.",
    "Solar panels were deployed in overlapping configurations.",
    "The communication tower transmitted farther than any predecessor.",
    "Structural beams distributed stress efficiently throughout.",
    "Viewports were positioned to maximize stellar observation.",
    "The asteroid provided high-quality mineral resources.",
    "Technicians constructed frameworks for the laboratory modules.",
    "The ventilation system circulated oxygen throughout the ship.",
    "Equipment was calibrated and tested at the facility.",
    "The corridor circled around the central core.",
    "Life support required redundant backup systems.",
    "The laboratory module adjoined the main living quarters.",
    "Composite materials supported the pressure-bearing structure.",
    "The airlock featured sophisticated decontamination systems.",
    "Calculations were verified repeatedly for accuracy.",
    "The workstations were positioned for optimal workflow.",
    "Shields reinforced the hull against radiation strategically.",
    "The main viewport dominated the observation deck.",
    "Systems were spaced according to engineering specifications.",
    "The corridor provided protected pathways for crew.",
    "Structural members converged at the central axis.",
    "The antenna array pointed precisely toward Earth.",
    "Access tubes spiraled throughout the ship's interior.",
    "The deck was constructed with anti-slip composite materials.",
    "Assembly followed the engineer's detailed schematics.",
]

all_expected_labels = (
    ["A"] * 40  # Hope/Aspiration
    + ["B"] * 40  # Conflict/Violence
    + ["C"] * 40  # Architecture/Building
)
