"""
Data Module - War and Peace Dataset
Contains training and test datasets for sentiment analysis based on "War and Peace" by Leo Tolstoy
Same categories as Sparrow dataset for comparison
"""

# Training Dataset (30 sentences inspired by "War and Peace" themes)
training_sentences = [
    "Pierre searched desperately for meaning in philosophy and religion.",
    "The French artillery bombarded Russian positions without mercy.",
    "Prince Andrei studied military strategy and tactical formations carefully.",
    "Natasha dreamed of finding true love and happiness.",
    "Cannon fire devastated the infantry ranks on the battlefield.",
    "Engineers constructed pontoon bridges across the river systematically.",
    "Sonya hoped her devotion would eventually be recognized.",
    "The cavalry charge broke through enemy lines with fury.",
    "Napoleon planned his campaign with calculated precision.",
    "Princess Marya prayed for her father's soul and forgiveness.",
    "Artillery units positioned their guns along the ridge.",
    "Cossacks slaughtered retreating soldiers in the snow.",
    "The general inspected fortifications and defensive positions.",
    "Count Rostov wished for his family's financial recovery.",
    "Bayonets clashed as infantry formations collided violently.",
    "Military engineers surveyed terrain for strategic advantage.",
    "Andrei aspired to achieve glory on the battlefield.",
    "The massacre at Borodino left thousands dead.",
    "Pierre observed the orbital mechanics of celestial bodies.",
    "Moscow burned as Napoleon's army approached the city.",
    "Nicholas vowed to restore his family's honor.",
    "Supplies were transported using horse-drawn wagons.",
    "Soldiers were cut down by grapeshot and musket fire.",
    "Prince Andrei longed for recognition and purpose.",
    "Field hospitals operated with primitive medical instruments.",
    "The retreat from Moscow became a death march.",
    "Kutuzov anticipated the enemy's movements through intelligence.",
    "Construction crews built winter quarters for troops.",
    "Artillery barrages preceded every major assault.",
    "Natasha yearned to understand her place in society.",
]

manual_labels = [
    "A", "B", "C", "A", "B", "C", "A", "B", "C", "A",
    "C", "B", "C", "A", "B", "C", "A", "B", "C", "B",
    "A", "C", "B", "A", "C", "B", "A", "C", "B", "A",
]

# Extended Test Dataset (120 sentences - inspired by "War and Peace")
all_test_sentences = [
    # Category A: Hope/Aspiration (40 sentences)
    "Pierre hoped to find spiritual enlightenment through freemasonry.",
    "Natasha dreamed of attending her first grand ball.",
    "Prince Andrei wished to prove himself in battle.",
    "Princess Marya prayed for peace and understanding.",
    "The young officer aspired to military distinction.",
    "Sonya longed for Nicholas to return her affection.",
    "Count Bezukhov sought meaning in philosophical studies.",
    "Natasha anticipated her debut in high society.",
    "Pierre vowed to become a better person.",
    "Andrei hoped to find purpose beyond vanity.",
    "The countess wished for her children's happiness.",
    "Nicholas dreamed of restoring family fortune.",
    "Marya aspired to spiritual purity and devotion.",
    "Pierre planned to reform his estates and serfs.",
    "Natasha yearned for passionate romantic love.",
    "Andrei envisioned a glorious military career.",
    "Sonya hoped to be accepted by the family.",
    "The young count wished for adventure and honor.",
    "Pierre sought answers in esoteric teachings.",
    "Marya prayed for her father's redemption.",
    "Natasha looked forward to the opera season.",
    "Andrei longed to escape domestic tedium.",
    "Nicholas vowed to win glory in cavalry service.",
    "Pierre hoped freemasonry would transform him.",
    "The princess wished for a worthy suitor.",
    "Natasha dreamed of a beautiful wedding.",
    "Andrei aspired to serve Russia with distinction.",
    "Sonya prayed for Nicholas's safe return.",
    "Pierre planned to implement enlightened reforms.",
    "Marya hoped to overcome her plainness through virtue.",
    "The young man wished to prove his courage.",
    "Natasha anticipated balls and social triumphs.",
    "Andrei longed for recognition from the Tsar.",
    "Pierre sought spiritual rebirth and renewal.",
    "The countess hoped her daughters would marry well.",
    "Nicholas dreamed of heroic cavalry charges.",
    "Marya prayed for humility and grace.",
    "Natasha yearned for life to begin at last.",
    "Andrei wished to leave a mark on history.",
    "Pierre hoped to find truth in philosophy.",
    # Category B: Conflict/Violence (40 sentences)
    "French soldiers pillaged the abandoned Russian village.",
    "Artillery fire shattered the infantry square brutally.",
    "Cossacks hunted down stragglers without mercy.",
    "The bayonet charge left bodies strewn across the field.",
    "Grapeshot tore through cavalry ranks with devastating effect.",
    "Russian troops burned bridges to slow the advance.",
    "Hand-to-hand combat raged through burning streets.",
    "Cannon balls crushed soldiers beneath rubble.",
    "The rearguard action became a desperate slaughter.",
    "Musket volleys cut down attacking columns.",
    "French cavalry trampled fleeing peasants underfoot.",
    "The siege guns bombarded Moscow relentlessly.",
    "Partisans ambushed supply convoys in the forest.",
    "Sabers clashed as cavalry squadrons collided.",
    "The assault wave was decimated by defensive fire.",
    "Wounded soldiers were abandoned in the snow.",
    "Russian batteries fired at point-blank range.",
    "The retreat became a massacre in frozen mud.",
    "Guerrillas attacked French patrols at night.",
    "Artillery duels destroyed entire villages.",
    "The charge was broken by concentrated musketry.",
    "Prisoners were executed to save supplies.",
    "Howitzers pounded the fortress walls to rubble.",
    "Cavalry sabers cut down infantry formations.",
    "The battle descended into savage close combat.",
    "Grapeshot massacred the attacking columns.",
    "Russian forces burned crops to deny the enemy.",
    "The bombardment lasted three days without pause.",
    "Soldiers froze to death during the retreat.",
    "French troops looted and burned estate houses.",
    "The counterattack was crushed with heavy losses.",
    "Cossack lances skewered retreating infantrymen.",
    "Artillery crews were overrun and slaughtered.",
    "The fortress fell after a brutal assault.",
    "Musket fire raked the advancing lines.",
    "The pursuit became a running massacre.",
    "Cavalry charges were repulsed with grapeshot.",
    "The city was sacked by occupying forces.",
    "Russian troops ambushed the baggage train.",
    "The final assault left thousands dead.",
    # Category C: Science/Technology/Military Organization (40 sentences)
    "Military engineers surveyed positions for artillery placement.",
    "The army organized supply depots along the route.",
    "Topographical maps were drawn with precise measurements.",
    "Field hospitals were established behind the lines.",
    "Artillery pieces were positioned on elevated ground.",
    "The general staff analyzed intelligence reports carefully.",
    "Pontoon bridges were constructed across major rivers.",
    "Signal fires communicated orders across distances.",
    "Wagons transported ammunition to forward positions.",
    "Engineers fortified defensive positions with earthworks.",
    "The quartermaster calculated supply requirements precisely.",
    "Artillery batteries were arranged in checkerboard formation.",
    "Reconnaissance units mapped enemy positions daily.",
    "Field kitchens prepared rations for thousands.",
    "Engineers measured trajectory angles for mortars.",
    "The ordnance department inspected weapon quality.",
    "Supply columns were organized in military order.",
    "Fortifications were designed with overlapping fields of fire.",
    "Military surgeons operated with available instruments.",
    "Artillery officers calculated range and elevation.",
    "The commissariat managed food distribution efficiently.",
    "Engineers constructed redoubts at strategic points.",
    "Signal flags coordinated troop movements precisely.",
    "Ammunition wagons were positioned near batteries.",
    "Topographers surveyed the battlefield terrain.",
    "The general headquarters coordinated multiple armies.",
    "Field artillery was calibrated for maximum range.",
    "Engineers reinforced bridges for heavy equipment.",
    "Supply trains followed predetermined routes.",
    "Artillery limbers were maintained in working order.",
    "The staff developed operational plans systematically.",
    "Fortifications incorporated the latest military designs.",
    "Medical orderlies organized triage procedures.",
    "Engineers calculated blast radius for explosives.",
    "The logistics corps transported siege equipment.",
    "Artillery parks stored reserve ammunition securely.",
    "Military architects designed defensive works.",
    "Supply officers requisitioned horses and fodder.",
    "Engineers installed telegraph lines for communications.",
    "The ordnance survey mapped strategic locations.",
]

all_expected_labels = (
    ["A"] * 40  # Hope/Aspiration
    + ["B"] * 40  # Conflict/Violence
    + ["C"] * 40  # Science/Technology/Military Organization
)
